"""Offline feature checks. Requires beautifulsoup4, playwright and Chromium.
Run from any directory: python scripts/check-noticing.py
Set CHROMIUM_EXECUTABLE only when a custom browser path is required.
Screenshots and test output go to a temporary directory, not the repository.
"""
from pathlib import Path
from bs4 import BeautifulSoup
import re, json, tempfile, shutil, hashlib, os
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
OUT=Path(tempfile.mkdtemp(prefix='woowooish-noticing-check-'))
html=(ROOT/'the-art-of-noticing/index.html').read_text(encoding='utf-8')
css=(ROOT/'assets/noticing.css').read_text(encoding='utf-8')
js=(ROOT/'assets/noticing.js').read_text(encoding='utf-8')
soup=BeautifulSoup(html,'html.parser')
checks=[]
def check(name, assertion):
    if not assertion: raise AssertionError(name)
    checks.append(name)
check('No authored em dash', all('\u2014' not in t for t in [html,css,js]))
check('One h1',len(soup.select('h1'))==1)
ids=[e['id'] for e in soup.select('[id]')]
check('Unique element IDs',len(ids)==len(set(ids)))
check('Internal anchors resolve',all(a['href'][1:] in ids for a in soup.select('a[href^="#"]')))
check('Every editable textarea has a label',all(soup.find('label',attrs={'for':e['id']}) for e in soup.select('textarea:not([readonly])')))
check('All five field notes in source',len(soup.select('.field-notes>details'))==5)
check('All nine invitations in source',len(soup.select('.prompt-columns li'))==9)
check('Seven optional weekly prompts',len(soup.select('.week-grid li'))==7)
check('Canonical URL',soup.select_one('link[rel=canonical]')['href']=='https://woowooish.com/the-art-of-noticing/')
check('Sharing image is approved portrait-free card',soup.select_one('meta[property="og:image"]')['content'].endswith('woowooish-share-20261006.png'))
check('No external scripts, forms, embeds or trackers',not soup.select('form,iframe') and all(e['src'].startswith('/assets/') for e in soup.select('script[src]')))
check('No network or persistent-storage APIs in enhancement',not re.search(r'\b(fetch|XMLHttpRequest|localStorage|sessionStorage|indexedDB|sendBeacon)\b|document\.cookie',js))
check('No fabricated Annie byline', not soup.select('[rel=author]') and 'not a personal account from Annie' in html)
test_html = html.replace('<link rel="stylesheet" href="/assets/fonts.css">', '')
test_html = test_html.replace('<link rel="stylesheet" href="/assets/noticing.css?v=20261007-1">', '<style>'+css+'</style>')
test_html = test_html.replace('<script src="/assets/noticing.js?v=20261007-1" defer></script>', '')
test_html = test_html.replace('</body>', '<script>'+js+'</script></body>')
with sync_playwright() as p:
    executable=os.environ.get('CHROMIUM_EXECUTABLE') or shutil.which('chromium')
    browser=p.chromium.launch(executable_path=executable,headless=True,args=['--no-sandbox'])
    context=browser.new_context(accept_downloads=True)
    page=context.new_page()
    errors=[]
    page.on('pageerror', lambda e:errors.append(str(e)))
    page.set_content(test_html)
    check('Enhancement controls exposed',page.locator('#notebook-actions').is_visible())
    for width in [320,360,390,768,1024,1440]:
        page.set_viewport_size({'width':width,'height':900})
        check(f'No horizontal overflow at {width}px',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    page.set_viewport_size({'width':1440,'height':1000})
    page.screenshot(path=str(OUT/'desktop-fallback-fonts.png'),full_page=True)
    page.set_viewport_size({'width':390,'height':844})
    page.screenshot(path=str(OUT/'mobile-fallback-fonts.png'),full_page=True)
    titles=set()
    for setting in ['home','outside','company']:
        page.locator(f'[data-setting={setting}]').click()
        check(f'{setting} pressed state',page.locator(f'[data-setting={setting}]').get_attribute('aria-pressed')=='true')
        first=page.locator('#invitation-title').inner_text()
        for _ in range(3):
            titles.add(page.locator('#invitation-title').inner_text())
            page.locator('#another-invitation').click()
        check(f'{setting} wraps deterministically',page.locator('#invitation-title').inner_text()==first)
    check('Nine distinct interactive invitations',len(titles)==9)
    page.locator('#copy-note').click()
    check('Empty note gives useful feedback','Add a few words' in page.locator('#note-status').inner_text())
    page.locator('#observed').fill('A patch of afternoon light.')
    page.locator('#felt').fill('Curious, and a little tired.')
    page.locator('#wondering').fill('What else have I passed by?')
    page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('denied')}}})")
    page.locator('#copy-note').click()
    check('Denied clipboard exposes manual fallback',page.locator('#manual-copy').is_visible())
    check('Fallback contains exact note','A patch of afternoon light.' in page.locator('#copy-text').input_value())
    page.locator('#felt').fill('A quieter kind of curiosity.')
    check('Editing hides stale copy preview',not page.locator('#manual-copy').is_visible())
    page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async t=>{window.copiedText=t}}})")
    page.locator('#copy-note').click()
    check('Successful copy includes note and canonical',page.evaluate("window.copiedText.includes('A quieter kind of curiosity.') && window.copiedText.includes('https://woowooish.com/the-art-of-noticing/')"))
    with page.expect_download() as got:
        page.locator('#save-note').click()
    downloaded=got.value
    downloaded.save_as(str(OUT/'download-test.txt'))
    check('Download is plain text with right name',downloaded.suggested_filename=='woowooish-field-note.txt')
    check('Downloaded note is complete','What else have I passed by?' in (OUT/'download-test.txt').read_text(encoding='utf-8'))
    page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>new Promise(r=>{window.finishCopy=r})}})")
    page.locator('#copy-note').click()
    page.locator('#clear-note').click()
    page.evaluate('window.finishCopy()')
    check('Late clipboard result cannot restore cleared status','Fields cleared' in page.locator('#note-status').inner_text())
    check('Clear erases fields and fallback',all(not page.locator('#'+i).input_value() for i in ['observed','felt','wondering','copy-text']))
    page.locator('#observed').fill('<script>window.bad=true</script>')
    page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async t=>{window.copiedText=t}}})")
    page.locator('#share-guide').click()
    check('Sharing contains only the guide link',page.evaluate("window.copiedText==='https://woowooish.com/the-art-of-noticing/'"))
    check('User input never executed as markup',not page.evaluate('Boolean(window.bad)'))
    page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('denied')}}})")
    page.locator('#share-guide').click()
    check('Share fallback works',page.locator('#share-fallback').is_visible())
    check('No JavaScript runtime errors',not errors)
    page.emulate_media(reduced_motion='reduce')
    check('Reduced motion removes smooth scrolling',page.evaluate("getComputedStyle(document.documentElement).scrollBehavior==='auto'"))
    # No-JavaScript reading and keyboard disclosure behavior.
    nojs=browser.new_context(java_script_enabled=False,viewport={'width':390,'height':844})
    np=nojs.new_page();np.set_content(test_html)
    check('No-JS guide remains readable',np.locator('h1').is_visible() and np.locator('#invitation-body').is_visible())
    check('No-JS inactive controls stay hidden',not np.locator('#notebook-actions').is_visible())
    np.locator('.prompt-library>summary').click()
    check('No-JS all nine prompts accessible',all(np.locator('.prompt-columns li').nth(i).is_visible() for i in range(9)))
    np.locator('.field-notes>details').nth(2).locator('summary').focus()
    np.keyboard.press('Enter')
    check('Keyboard opens native field note',np.locator('.field-notes>details').nth(2).get_attribute('open') is not None)
    reflection_js=(ROOT/'assets/reflections.js').read_text(encoding='utf-8')
    original=reflection_js.split('\n// A small, independent discovery card.')[0].encode()
    original_sha=hashlib.sha1(f'blob {len(original)}\0'.encode()+original).hexdigest()
    check('Existing reflection enhancement preserved byte-for-byte',original_sha=='a4c1c9c8359181312928b1ad4f1f5dc223aa099b')
    hp=context.new_page()
    fixture='<html><head><style>*{box-sizing:border-box}body{margin:0}</style></head><body><section id="start-here"><h2>Start here</h2></section><section id="daily-woo">Daily Woo</section><article class="reflection-card" id="sample"><p class="reflection-prompt">What did you notice?</p><button data-copy-note="question" hidden>Copy question</button><p class="note-status"></p><textarea class="note-copy" hidden></textarea></article></body></html>'
    hp.set_content(fixture)
    hp.add_script_tag(content=reflection_js)
    check('Homepage discovery link resolves to new path',hp.locator('#noticing-feature a').get_attribute('href')=='/the-art-of-noticing/')
    check('Discovery card appears after Start here',hp.evaluate("document.getElementById('start-here').nextElementSibling.id==='noticing-feature'"))
    check('Existing Daily Woo keeps its relative position',hp.evaluate("document.getElementById('noticing-feature').nextElementSibling.id==='daily-woo'"))
    for width in [320,390,768,1440]:
        hp.set_viewport_size({'width':width,'height':900})
        check(f'Homepage card has no overflow at {width}px',hp.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    hp.locator('[data-copy-note]').click()
    check('Existing reflection copy fallback still works',hp.locator('.note-copy').input_value()=='What did you notice?')
    hp.add_script_tag(content=reflection_js)
    check('Discovery card does not duplicate',hp.locator('#noticing-feature').count()==1)
    browser.close()
report={'artifact_directory':str(OUT),'checks_passed':len(checks),'checks':checks,'limitations':['Offline layout checks intentionally inline only the new CSS and JS. Shared fonts and photographs require separate live visual verification.','This is a focused feature test, not a replacement for the repository-wide checks or live deployment verification.']}
(OUT/'local-test-results.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
print(json.dumps(report,indent=2))
