"""Offline feature checks. Requires beautifulsoup4, playwright and Chromium.
Run from any directory: python scripts/check-noticing.py
Set CHROMIUM_EXECUTABLE only when a custom browser path is required.
Screenshots and test output go to a temporary directory, not the repository.
"""
from pathlib import Path
from bs4 import BeautifulSoup
import re, json, tempfile, shutil, hashlib, os, base64, mimetypes
from playwright.sync_api import sync_playwright
ROOT=Path(__file__).resolve().parents[1]
OUT=Path(tempfile.mkdtemp(prefix='woowooish-noticing-check-'))
html=(ROOT/'the-art-of-noticing/index.html').read_text(encoding='utf-8')
css=(ROOT/'assets/noticing.css').read_text(encoding='utf-8')
js=(ROOT/'assets/noticing.js').read_text(encoding='utf-8')
soup=BeautifulSoup(html,'html.parser')
checks=[]
def check(name, assertion):
    if not assertion: raise AssertionError(name)
    checks.append(name)
check('No authored em dash', all('\u2014' not in t for t in [html,css,js]))
check('One h1',len(soup.select('h1'))==1)
ids=[e['id'] for e in soup.select('[id]')]
check('Unique element IDs',len(ids)==len(set(ids)))
check('Internal anchors resolve',all(a['href'][1:] in ids for a in soup.select('a[href^="#"]')))
check('Every editable textarea has a label',all(soup.find('label',attrs={'for':e['id']}) for e in soup.select('textarea:not([readonly])')))
check('All five field notes in source',len(soup.select('.field-notes>details'))==5)
check('All nine invitations in source',len(soup.select('.prompt-columns li'))==9)
check('Seven optional weekly prompts',len(soup.select('.week-grid li'))==7)
check('Canonical URL',soup.select_one('link[rel=canonical]')['href']=='https://woowooish.com/the-art-of-noticing/')
check('Sharing image is approved portrait-free card',soup.select_one('meta[property="og:image"]')['content'].endswith('woowooish-share-20261006.png'))
check('No external scripts, forms, embeds or trackers',not soup.select('form,iframe') and all(e['src'].startswith('/assets/') for e in soup.select('script[src]')))
check('No network or persistent-storage APIs in enhancement',not re.search(r'\b(fetch|XMLHttpRequest|localStorage|sessionStorage|indexedDB|sendBeacon)\b|document\.cookie',js))
check('No fabricated Annie byline', not soup.select('[rel=author]') and 'not a personal account from Annie' in html)
# Render exact production assets offline, including the approved fonts and portrait.
def data_url(path):
    media_type = mimetypes.guess_type(path.name)[0] or 'application/octet-stream'
    return 'data:' + media_type + ';base64,' + base64.b64encode(path.read_bytes()).decode()
def inline_styles(match):
    path = ROOT / match[1].split('?')[0].lstrip('/')
    style = path.read_text(encoding='utf-8')
    def font_url(match):
        value = match[1].strip('"' + "'")
        if value.startswith(('data:', 'http:','https:')): return match[0]
        return 'url("' + data_url((path.parent / value).resolve()) + '")'
    style = re.sub(r'url\(([^)]+)\)', font_url, style)
    return '<style>' + style + '</style>'
# The production policy is verified separately; test instrumentation inlines assets and needs evaluable scripts.
fixture_html = re.sub(r'<meta http-equiv="Content-Security-Policy"[^>]*>', '', html)
test_html = re.sub(r'<link rel="stylesheet" href="([^"]+)">', inline_styles, fixture_html)
# Inline fixtures cannot inherit the production origin; policy has a separate test.
test_html = re.sub(r'<meta http-equiv="Content-Security-Policy"[^>]*>', '', test_html)
test_html = re.sub(r'(<img[^>]+src=")([^"]+)(")', lambda m: m[1]+data_url(ROOT / m[2].lstrip('/'))+m[3], test_html)
test_html = re.sub(r'<script src="/assets/noticing\.js(?:\?[^"]*)?" defer></script>', '', test_html)
test_html = test_html.replace('</body>', '<script>'+js+'</script></body>')
with sync_playwright() as p:
    executable=os.environ.get('CHROMIUM_EXECUTABLE') or shutil.which('chromium')
    browser=p.chromium.launch(executable_path=executable,headless=True,args=['--no-sandbox'])
    context=browser.new_context(accept_downloads=True)
    page=context.new_page()
    errors=[]
    page.on('pageerror', lambda e:errors.append(str(e)))
    page.set_content(test_html)
    page.evaluate('document.fonts.ready')
    check('Original portrait loads', page.locator('.portrait img').evaluate('(e)=>e.complete && e.naturalWidth===1254'))
    check('Brand fonts loaded', page.evaluate("document.fonts.check('800 20px Bricolage Grotesque') && document.fonts.check('400 12px Space Mono')"))
    check('Enhancement controls exposed',page.locator('#notebook-actions').is_visible())
    for width in [320,360,390,768,1024,1440]:
        page.set_viewport_size({'width':width,'height':900})
        check(f'No horizontal overflow at {width}px',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    page.set_viewport_size({'width':1440,'height':1000})
    page.screenshot(path=str(OUT/'desktop-production-assets.png'),full_page=True)
    page.set_viewport_size({'width':390,'height':844})
    page.screenshot(path=str(OUT/'mobile-production-assets.png'),full_page=True)
    titles=set()
    for setting in ['home','outside','company']:
        page.locator(f'[data-setting={setting}]').click()
        check(f'{setting} pressed state',page.locator(f'[data-setting={setting}]').get_attribute('aria-pressed')=='true')
        first=page.locator('#invitation-title').inner_text()
        for _ in range(3):
            titles.add(page.locator('#invitation-title').inner_text())
            page.locator('#another-invitation').click()
        check(f'{setting} wraps deterministically',page.locator('#invitation-title').inner_text()==first)
    check('Nine distinct interactive invitations',len(titles)==9)
    page.locator('#copy-note').click()
    check('Empty note gives useful feedback','Add a few words' in page.locator('#note-status').inner_text())
    page.locator('#observed').fill('A patch of afternoon light.')
    page.locator('#felt').fill('Curious, and a little tired.')
    page.locator('#wondering').fill('What else have I passed by?')
    page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('denied')}}})")
    page.locator('#copy-note').click()
    check('Denied clipboard exposes manual fallback',page.locator('#manual-copy').is_visible())
    check('Fallback contains exact note','A patch of afternoon light.' in page.locator('#copy-text').input_value())
    page.locator('#felt').fill('A quieter kind of curiosity.')
    check('Editing hides stale copy preview',not page.locator('#manual-copy').is_visible())
    page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async t=>{window.copiedText=t}}})")
    page.locator('#copy-note').click()
    check('Successful copy includes note and canonical',page.evaluate("window.copiedText.includes('A quieter kind of curiosity.') && window.copiedText.includes('https://woowooish.com/the-art-of-noticing/')"))
    with page.expect_download() as got:
        page.locator('#save-note').click()
    downloaded=got.value
    downloaded.save_as(str(OUT/'download-test.txt'))
    check('Download is plain text with right name',downloaded.suggested_filename=='woowooish-field-note.txt')
    check('Downloaded note is complete','What else have I passed by?' in (OUT/'download-test.txt').read_text(encoding='utf-8'))
    page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>new Promise(r=>{window.finishCopy=r})}})")
    page.locator('#copy-note').click()
    page.locator('#clear-note').click()
    page.locator('#confirm-clear').click()
    page.evaluate('window.finishCopy()')
    check('Late clipboard result cannot restore cleared status','Fields cleared' in page.locator('#note-status').inner_text())
    check('Clear erases fields and fallback',all(not page.locator('#'+i).input_value() for i in ['observed','felt','wondering','copy-text']))
    page.locator('#observed').fill('<script>window.bad=true</script>')
    page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async t=>{window.copiedText=t}}})")
    page.locator('#share-guide').click()
    check('Sharing contains only the guide link',page.evaluate("window.copiedText==='https://woowooish.com/the-art-of-noticing/'"))
    check('User input never executed as markup',not page.evaluate('Boolean(window.bad)'))
    page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw new Error('denied')}}})")
    page.locator('#share-guide').click()
    check('Share fallback works',page.locator('#share-fallback').is_visible())
    # Connected prompts and deliberately confirmed clearing.
    check('Quick-start has three source steps', len(soup.select('.small-start-steps li')) == 3)
    check('Five stable field-note links', len(soup.select('.field-notes > details[id]')) == 5)
    page.locator('#observed').fill('My own words, not a suggested answer.')
    page.locator('#felt').fill('Both grateful and tired.')
    page.locator('[data-setting=outside]').click()
    question = page.locator('#invitation-question').inner_text()
    page.locator('#carry-invitation').click()
    check('Invitation question carried to notebook', page.locator('#carried-question-text').inner_text()==question)
    check('Carrying a prompt preserves writing', page.locator('#observed').input_value()=='My own words, not a suggested answer.')
    check('Carrying moves keyboard focus to writing', page.locator('#observed').evaluate('(e)=>e===document.activeElement'))
    page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async t=>{window.copiedText=t}}})")
    page.locator('#copy-note').click()
    check('Copy includes carried question', question in page.evaluate('window.copiedText'))
    with page.expect_download() as got_with_prompt:
        page.locator('#save-note').click()
    got_with_prompt.value.save_as(str(OUT/'prompt-download-test.txt'))
    check('Download includes carried question', question in (OUT/'prompt-download-test.txt').read_text(encoding='utf-8'))
    page.locator('#clear-note').click()
    check('Clear asks before removing writing', page.locator('#clear-confirm').is_visible() and bool(page.locator('#observed').input_value()))
    check('Confirmation focuses safe keep-writing action', page.locator('#cancel-clear').evaluate('(e)=>e===document.activeElement'))
    page.keyboard.press('Escape')
    check('Escape dismisses confirmation without clearing', not page.locator('#clear-confirm').is_visible() and bool(page.locator('#observed').input_value()))
    page.locator('#clear-note').click()
    page.locator('#cancel-clear').click()
    check('Keep writing preserves carried question', page.locator('#carried-question-text').inner_text()==question)
    page.locator('#clear-note').click()
    page.locator('#felt').fill('Changed after the confirmation appeared.')
    check('Editing invalidates pending clear confirmation', not page.locator('#clear-confirm').is_visible())
    page.evaluate("document.getElementById('confirm-clear').click()")
    check('Stale clear action cannot erase new writing', page.locator('#felt').input_value()=='Changed after the confirmation appeared.')
    page.locator('#remove-prompt').click()
    check('Removing question preserves note', not page.locator('#carried-prompt').is_visible() and bool(page.locator('#observed').input_value()))
    page.locator('#copy-note').click()
    check('Removed question is excluded from copies', 'A QUESTION TO KEEP ME COMPANY' not in page.evaluate('window.copiedText'))
    page.evaluate("window.location.hash='#note-open-question'")
    page.wait_for_function("document.getElementById('note-open-question').open")
    check('Direct field-note link opens correct disclosure', page.locator('#note-open-question').get_attribute('open') is not None)
    check('Direct link moves keyboard focus to summary', page.locator('#note-open-question>summary').evaluate('(e)=>e===document.activeElement'))
    page.locator('#note-open-question [data-reflect-note]').click()
    check('Field-note question carries without label prefix', page.locator('#carried-question-text').inner_text()=='Which question would I like to keep company with, rather than solve today?')
    page.locator('#share-guide').click()
    check('Sharing excludes both note and carried prompt', page.evaluate("window.copiedText==='https://woowooish.com/the-art-of-noticing/'"))
    page.locator('#clear-note').click()
    page.locator('#confirm-clear').click()
    check('Confirmed clear erases writing and question', all(not page.locator('#'+i).input_value() for i in ['observed','felt','wondering','copy-text']) and not page.locator('#carried-prompt').is_visible() and not page.locator('#carried-question-text').inner_text())
    # Every field-note prompt should be carried as text, not HTML.
    for note_id in ['note-beginners-eyes','note-two-feelings','note-curiosity','note-kindness','note-open-question']:
        page.evaluate('(id)=>document.getElementById(id).open=true',note_id)
        page.locator('#'+note_id+' [data-reflect-note]').click()
        check(note_id+' question is usable', len(page.locator('#carried-question-text').inner_text()) > 20)
    initial=context.new_page()
    initial.goto('about:blank#note-curiosity')
    initial.set_content(test_html)
    check('Fresh page visit opens linked note',initial.locator('#note-curiosity').get_attribute('open') is not None)
    initial.close()
    page.locator('#observed').fill('Keep my writing while I change prompts.')
    page.evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>new Promise(r=>{window.finishPromptCopy=r})}})")
    page.locator('#copy-note').click()
    page.locator('#note-kindness [data-reflect-note]').click()
    page.evaluate('window.finishPromptCopy()')
    check('Changing prompt invalidates late clipboard status','Question added' in page.locator('#note-status').inner_text())
    for width in [320,390,768,1440]:
        page.set_viewport_size({'width':width,'height':900})
        check(f'Expanded notes and carried prompt fit at {width}px',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    check('No persistent note storage created', not re.search(r'\b(localStorage|sessionStorage|indexedDB|sendBeacon|XMLHttpRequest|fetch)\b',js))
    check('No JavaScript runtime errors',not errors)
    page.emulate_media(reduced_motion='reduce')
    check('Reduced motion removes smooth scrolling',page.evaluate("getComputedStyle(document.documentElement).scrollBehavior==='auto'"))
    # No-JavaScript reading and keyboard disclosure behavior.
    nojs=browser.new_context(java_script_enabled=False,viewport={'width':390,'height':844})
    np=nojs.new_page();np.set_content(test_html)
    check('No-JS guide remains readable',np.locator('h1').is_visible() and np.locator('#invitation-body').is_visible())
    check('Quick start works without JavaScript',np.locator('#small-start-title').is_visible() and np.locator('.small-start-steps li').count()==3)
    check('No-JS new interactive controls stay hidden',not np.locator('#carry-invitation').is_visible() and not np.locator('[data-reflect-note]').first.is_visible())
    check('No-JS inactive controls stay hidden',not np.locator('#notebook-actions').is_visible())
    np.locator('.prompt-library>summary').click()
    check('No-JS all nine prompts accessible',all(np.locator('.prompt-columns li').nth(i).is_visible() for i in range(9)))
    np.locator('.field-notes>details').nth(2).locator('summary').focus()
    np.keyboard.press('Enter')
    check('Keyboard opens native field note',np.locator('.field-notes>details').nth(2).get_attribute('open') is not None)
    reflection_js=(ROOT/'assets/reflections.js').read_text(encoding='utf-8')
    original=reflection_js.split('\n// A small, independent discovery card.')[0].encode()
    original_sha=hashlib.sha1(f'blob {len(original)}\0'.encode()+original).hexdigest()
    check('Existing reflection enhancement preserved byte-for-byte',original_sha=='a4c1c9c8359181312928b1ad4f1f5dc223aa099b')
    hp=context.new_page()
    fixture='<html><head><style>*{box-sizing:border-box}body{margin:0}</style></head><body><section id="start-here"><h2>Start here</h2></section><section id="daily-woo">Daily Woo</section><article class="reflection-card" id="sample"><p class="reflection-prompt">What did you notice?</p><button data-copy-note="question" hidden>Copy question</button><p class="note-status"></p><textarea class="note-copy" hidden></textarea></article></body></html>'
    hp.set_content(fixture)
    hp.add_script_tag(content=reflection_js)
    check('Homepage discovery link resolves to new path',hp.locator('#noticing-feature a').get_attribute('href')=='/the-art-of-noticing/')
    check('Discovery card appears after Start here',hp.evaluate("document.getElementById('start-here').nextElementSibling.id==='noticing-feature'"))
    check('Existing Daily Woo keeps its relative position',hp.evaluate("document.getElementById('noticing-feature').nextElementSibling.id==='daily-woo'"))
    for width in [320,390,768,1440]:
        hp.set_viewport_size({'width':width,'height':900})
        check(f'Homepage card has no overflow at {width}px',hp.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    hp.locator('[data-copy-note]').click()
    check('Existing reflection copy fallback still works',hp.locator('.note-copy').input_value()=='What did you notice?')
    hp.add_script_tag(content=reflection_js)
    check('Discovery card does not duplicate',hp.locator('#noticing-feature').count()==1)
    browser.close()
report={'artifact_directory':str(OUT),'checks_passed':len(checks),'checks':checks,'limitations':['Browser checks inline exact production HTML, CSS, JavaScript, brand fonts and portrait for offline rendering. They do not prove live CDN freshness or browser coverage beyond Chromium.','This is a focused feature test, not a replacement for the repository-wide checks or live deployment verification.']}
(OUT/'local-test-results.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf-8')
print(json.dumps(report,indent=2))
